development:
  host: localhost
  database: buskw_api_development

test:
  host: localhost
  database: buskw_api_test

production:
  host: ENV['DB_HOST']
  database: ENV['DB_NAME']
  port: ENV['DB_PORT']
  username: ENV['DB_USER']
  password: ENV['DB_PASSWORD']